# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2

mkdocs:
  configuration: mkdocs.yaml

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_system_dependencies:
    - git fetch --unshallow   # Needed to get version tags
    pre_install:
    - pip install mkdocs-material

python:
  install:
  - requirements: doc/requirements.txt
