# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.8.0
tutorial: true


countries: ["NG", "BJ"]

enable:
  retrieve_databundle: true
  retrieve_databundle_sector: true
  retrieve_cutout: true
  build_natura_raster: true
  progress_bar: false

scenario:
  clusters: [6]
  opts: [Co2L-4H]

snapshots:
  start: "2013-03-1"
  end: "2013-03-7"


osm:
  clean_osm_data:
    threshold_voltage: 35000

base_network:
  min_voltage_substation_offshore: 35000
  min_voltage_rebase_voltage: 35000


co2:
  limit: 1.487e+9
  base: 1.487e+9
  automatic_emission:
    enable: true


atlite:
  default: cutout-2013-era5-tutorial

renewable:
  hydro:
    hydrobasins_level: 4
    hydro_max_hours: "energy_capacity_totals_by_country"
    resource:
      method: hydro
      hydrobasins: data/hydrobasins_hydroshare/africa-geoglows-atlite.shp

custom_data:
    osm_data: false # if "True" then custom file for osm (pbf and power files) must be placed in "data/custom/osm" folder. 

# OpenStreetMap (OSM) data configuration
osm_data:
  source: "latest" # Options: "latest", "historical", or "custom"
  custom_path:
    pbf: "data/custom/osm/pbf"  # Path to pbf files (required if source: "custom")
    power: "data/custom/osm/power"  # Path to power files (optional)
  target_date: # e.g., "2020-01-01" (used when source: "historical")

solving:
  solver:
    name: glpk
    options: glpk-default
