# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

run:
  name: tutorial.test
  sector_name: tutorial
  base_config: config.tutorial.yaml  # base configuration file
  shared_cutouts: true
