blank_issues_enabled: false
contact_links:
- name: Discussion board
  url: https://github.com/open-energy-transition/pypsa-zambia/discussions
  about: Please ask and answer general usage questions here.
