name: Deploy MkDocs site to GitHub Pages

on:
  # Trigger the workflow manually
  workflow_dispatch:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
      - dev/asean_v0
      - scenario/paper_v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          mkdocs build -f doc-asean/mkdocs.yml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: doc-asean/site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
